export const BlogData = [
    {
        id: 1,
        title: "Inland freight a worthy solution for your business",
        desc: "We are dedicated in creating added value for our customers by implementing modern technology in our work.",
        readingTime: "4 min read",
        publishedDate: "24 Jan",
        image: "/assets/Blog/blog1.jpg",
    },
    {
        id: 2,
        title: "Following the quality of our service thus having gained trust of our many clients.",
        desc: "We are dedicated in creating added value for our customers by implementing modern technology in our work.",
        readingTime: "3 min read",
        publishedDate: "24 Jan",
        image: "/assets/Blog/blog2.jpg",
    },
    {
        id: 3,
        title: "Our global logistics expertise, advanced supply chain technology & customized solutions.",
        desc: "Logistics solutions will help you analyze, develop and implement successful supply chain management strategies.",
        readingTime: "3 min read",
        publishedDate: "24 Jan",
        image: "/assets/Blog/blog3.jpg",
    },
    {
        id: 4,
        title: "5 Ways Logistics Tech is Transforming Supply Chains",
        desc: "Discover how cutting-edge logistics technology is improving efficiency, reducing delays, and transforming global supply chains.",
        readingTime: "4 min read",
        publishedDate: "24 Jan",
        image: "/assets/blogs/logistics-tech.jpg",
    },
    {
        id: 5,
        title: "How to Minimize Shipping Delays in 2025",
        desc: "Practical strategies and tools that help businesses avoid common causes of delays in international and domestic shipping.",
        readingTime: "3 min read",
        publishedDate: "24 Jan",
        image: "/assets/blogs/shipping-delays.jpg",
    },
    {
        id: 6,
        title: "Sustainable Logistics: The Road Ahead",
        desc: "Explore the growing impact of sustainability on logistics and what companies are doing to reduce their carbon footprint.",
        readingTime: "5 min read",
        publishedDate: "24 Jan",
        image: "/assets/blogs/sustainable-logistics.jpg",
    },
    {
        id: 7,
        title: "Choosing Between Air and Sea Freight",
        desc: "A quick guide to help you decide the best mode of shipping for your needs—based on cost, speed, and reliability.",
        readingTime: "2 min read",
        publishedDate: "24 Jan",
        image: "/assets/blogs/air-vs-sea.jpg",
    },
];
