import {
  FaBarcode,
  FaCheckCircle,
  FaBoxOpen,
  FaSortAmountDown,
  FaUndoAlt,
  FaChartBar,
  FaBoxes,
  FaArrowsAltV,
  FaTags,
  FaTruckMoving,
  FaTshirt,
  FaPuzzlePiece,
} from "react-icons/fa";

export const valueAddedServices = [
  // {
  //   id: 1,
  //   image: "/assets/Services/VAS/scanning.jpg",
  //   icon: FaBarcode,
  //   title: "Scannen",
  //   desc: "Das Scannen der Fracht erfolgt gemäß Ihren Anforderungen.",
  // },
  {
    id: 2,
    image: "/assets/Services/VAS/quality-controls.jpg",
    icon: FaCheckCircle,
    title: "Qualitätskontrollen",
    desc: "Wir unterstützen Sie bei der Durchführung von Betriebstechniken und -aktivitäten an der Fracht, um Ihre Qualitätsanforderungen zu erfüllen.",
  },
  {
    id: 3,
    image: "/assets/Services/VAS/repackaging.jpg",
    icon: FaBoxOpen,
    title: "Umverpackung",
    desc: "Wir unterstützen Sie beim Verpacken oder Umpacken Ihrer Fracht nach Ihren Vorgaben.",
  },
  // {
  //   id: 4,
  //   image: "/assets/Services/VAS/cargo-sorting.jpg",
  //   icon: FaSortAmountDown,
  //   title: "Frachtsortierung",
  //   desc: "Wir führen die Frachtsortierung nach Ihren Wünschen in unseren Anlagen durch.",
  // },
  {
    id: 5,
    image: "/assets/Services/VAS/return-management.jpg",
    icon: FaUndoAlt,
    title: "Retourenmanagement",
    desc: "Wir unterstützen Sie bei der Verwaltung Ihrer Warenrückläufe im Lager.",
  },
  {
    id: 6,
    image: "/assets/Services/VAS/reporting.jpg",
    icon: FaChartBar,
    title: "Berichterstellung",
    desc: " Wir sorgen durch die Erstellung individueller Berichte für Transparenz in Ihrem Bestand.",
  },
  {
    id: 7,
    image: "/assets/Services/VAS/palletizing.jpg",
    icon: FaBoxes,
    title: "Palettierung",
    desc: "Wir unterstützen Sie bei der Lagerung und dem Transport von auf Paletten gestapelter Fracht.",
  },
  // {
  //   id: 8,
  //   image: "/assets/Services/VAS/shaving.jpg",
  //   icon: FaArrowsAltV,
  //   title: "Paletten abtragen/auffüllen",
  //   desc: " Die Höhe einer Palette wird durch Entfernen der oberen Kartonlagen angepasst.",
  // },
  {
    id: 9,
    image: "/assets/Services/VAS/labelling.jpg",
    icon: FaTags,
    title: " Etikettierung",
    desc: "Druck und Platzierung von Etiketten nach Ihren Wünschen.",
  },
  {
    id: 10,
    image: "/assets/Services/VAS/yard-management.jpg",
    icon: FaTruckMoving,
    title: "Lagerplatzmanagement",
    desc: "An unseren Standorten können LKW/Container auf dem Lagerplatz effektiv verwaltet werden.",
  },
  // {
  //   id: 11,
  //   image: "/assets/Services/VAS/customization.jpg ",
  //   icon: FaTshirt,
  //   title: "Kleidungsstücke auf Kleiderbügeln",
  //   desc: "Unsere Einrichtungen sind für die Handhabung hängender Kleidungsstücke auf Kleiderständern/Kleiderstangen ausgestattet.",
  // },
  {
    id: 12,
    image: "/assets/Services/VAS/garmnets.jpg",
    icon: FaPuzzlePiece,
    title: "Produktanpassung",
    desc: "Mit unseren Individualisierungsservices können Sie Pakete genau nach Ihren Bedürfnissen zusammenstellen. ",
  },
];
